package ;

import coconut.data.*;
import tink.pure.List;
import js.html.*;
import js.Browser.*;
import vdom.VDom.*;
import vdom.VNode;

using tink.CoreApi;

class TodoMvc {
  static function main() {
    var item = TodoItem.create('test');
    // var view = new TodoItemView(item);
    // var data = new TodoList({ items: [] });
    // var view = new TodoListView(data);
    // document.body.appendChild(view.toElement());
  }
}

class TodoItem implements Model {
  
  @:editable var completed:Bool = @byDefault false;
  @:editable var description:String;

  @:constant var created:Date = @byDefault Date.now();

  static public function create(description:String) 
    return new TodoItem({ description: description });//Constructor is autogenerated

  static public function isActive(item:TodoItem)
    return !item.completed;

  static public function isCompleted(item:TodoItem)
    return item.completed;

}

class TodoList implements Model {

  @:observable var items:List<TodoItem>;

  @:transition function add(description:String) 
    items = items.prepend(TodoItem.create(description));
  
  @:transition function clearCompleted() 
    items = items.filter(i => !i.completed);

}

class TodoFilter implements Model {
  @:constant var options:List<Named<TodoItem->Bool>> = [
    new Named('All', _ => true),
    new Named('Active', TodoItem.isActive),
    new Named('Completed', TodoItem.isCompleted),
  ];

  @:observable var currentFilter:TodoItem->Bool = options.iterator().next().value;

  public function matches(item:TodoItem):Bool
    return currentFilter(item);

  @:transition function toggle(filter:TodoItem->Bool) {
    for (o in options)
      if (o.value == filter) currentFilter = filter;

    throw 'this should not happen';
  }
  
  public function isActive(filter:TodoItem->Bool)
    return filter == currentFilter;
}

class TodoItemView extends coconut.ui.View<TodoItem> {
  function render(item:TodoItem):VNode return @hxx '
    <div class="todo-item" data-completed={item.completed}>
      <input type="checkbox" checked={item.completed} onchange={e => item.completed = e.target.checked} />
      <input type="name" value={item.description} onchange={e => item.description = e.target.value} />
    </div>
  ';
}